Test
Altu-Bitu/Kimyu pull request #10
Opened 2021-10-01 08:39 UTC by kimyu0218

1149번, 2294번, 3190번, 10844번, 15486번, 17404번, 20923번 풀었습니다!

2021-10-01 08:49 UTC, kimyu0218 commented
+) 2565번은 예제는 잘 되는 것 같은데 9% 정도에서 틀렸습니다가 나옵니다. 혹시 제가 구상 자체를 잘못한 건까요..?

a번 전깃줄 위치를 오름차순 정렬한 상태에서 b번 전깃줄 위치를 비교했습니다. b번의 전깃줄 번호도 오름차순으로 되어야 전깃줄 교차가 일어나지 않을 것이라고 생각해서 증가하는 수열을 찾도록 했습니다. 예제를 바탕으로 출력했을 때 다음과 같이 나와요!
a번: 1	2	3	4	6	7	9	10
b번: 8	2	9	1	4	6	7	10
dp:  1	1	2	1	2	3	4	5

2021-10-01 10:39 UTC, HyunJiLim0406 requested changes
p2(2565 제외)
수고하셨습니다! 2565번은 점화식을 잘못 짜신 것 같습니다! 코멘트 달았으니 확인해주세요~
20923번도 중복되는 부분 리팩토링해볼 수 있구요!
수정 후 리뷰어로 저 호출해주세요~

2021-10-01 10:39 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/10844.cpp
> +int dp[MAX+1][10];
이건 countStairs 함수에서만 쓰니까 지역변수로 들어가도 돼요!

2021-10-01 10:39 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/10844.cpp
> +            else dp[i][j] = (dp[i-1][j-1] + dp[i-1][j+1]) % Q;
👍

2021-10-01 10:39 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/15486.cpp
> +    }
아하 이게 어떻게 가능한가 했더니 dp 크기를 넉넉하게 잡으셨네요! 좋은 방법이에요~

2021-10-01 10:39 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/17404.cpp
> +            if(j != i) min_cost = min(min_cost, dp[n][j]); // 1�� �� ���� ��ġ�� �ʴ� ���
함수를 만드는 목적은 인덴테이션이 깊어지는걸 방지하기 위해서기도 해요!
이 함수에는 이 부분만 남기고 메인에서 첫번째 집의 색을 정해서 넘겨주면 어떨까요?

2021-10-01 10:39 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/20923.cpp
> +    }
이 부분은 중복이 많네요!
중복을 없애면 while문도 true가 아니라 (m--)등으로 처리할 수 있을 것 같아요
순서는 도도이거나, 도도가 아니거나로도 표현할 수도 있어요!

2021-10-01 10:39 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/20923.cpp
> +    }
여기서 winner가 도도인지/아닌지만 정하면 중복 코드가 없어져요

2021-10-01 10:39 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/20923.cpp
> +int main() {
p2
중복 코드를 없앨 힌트를 드리겠습니다! 앞서 말했듯이 이번 순서는 도도거나/도도가 아니거나로 표현할 수 있어요
덱 관리 방법을 바꾸면 중복이 없어지는데요, 저희 스택때 크레인 문제 기억나시나요?

2021-10-01 10:39 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/2565.cpp
> +        result = max(result, dp[i]);
음 이건 연속해서 값이 증가하는 경우만 확인하는 것처럼 보이네요!
i, j에 대해 dp[j]가 1이 아니어도 dp[i] > dp[j]일 수도 있어요!
증가하는 수열이라면 저희가 점화식을 배웠던 것 같아요~

2021-10-01 10:39 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/3190.cpp
> +bool apple[SIZE+1][SIZE+1], body[SIZE+1][SIZE+1];
bool을 사용하지 않으면 apple과 body를 함께 처리할 수 있어요!

2021-10-01 14:55 UTC, kimyu0218 commented
2565번, 3190번, 10844번, 17404번, 20923번 수정했습니다!!

+) 2565번에서 inc라는 변수를 따로 사용해서 증가 수열의 최대 길이를 구했습니다. dp에 증가 수열의 최대 길이를 바로 저장하는 방법은 없나요?? 
항상 상세하게 리뷰 달아주셔서 감사합니다 ㅎㅎ

2021-10-02 02:36 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 다 잘 수정해주셨어요

2565번에서 증가 수열의 최대 길이를 바로 저장하는 방법이 있어요!
근데 그건 점화식을 바꾸셔야해요. 동적계획법을 처음 배우시는 입장에선 어려우실 수도 있을 것 같아 수업에선 다루지 않았고, 저희 샘플코드로는 준비했는데요. 구현 힌트를 드릴게요. 이건 약간 그리디적 사고가 필요한 점화식이에요!

1 10 3 8 15 13 7
이라는 수열이 있다고 할게요! 지금 구현 방법대로 dp를 구하면

1 2 2 3 4 4 3
이 될거예요.

근데 사실 15는 15 이전에 있던 숫자들 중에 dp 값이 가장 컸던 8보다 크다는 사실만 확인되면 바로 dp 값이 4라고 처리하고 넘어가도 괜찮아요! 7은 어떨까요? 15와 13중에 뭐랑 비교하는게 좋을까요? 어차피 둘 다 dp값이 4라면 그보다 작은 값과 비교하면 어떨까요? 어차피 13보다 크기만 해도 dp값이 5가 되는거니까요!
아쉽게도 13보다는 작네요. 8보다도 작으니까 넘어가서 그럼 이번엔 10과 3 중에 뭐랑 비교하는게 좋을까요? 3일거예요!

구현 아이디어가 떠오르셨을까요? 결정적인 힌트는 이 방법을 쓰면 증가 수열의 최대 길이를 바로 알 수 있다는거예요~

코드들은 이미 다 잘 작성해주셔서 이대로 머지하셔도 좋습니다!
혹시 이 아이디어로 구현을 해보고 싶으신다면 수정 후 리뷰어로 저 요청하셔도 너무 좋구요!
일단 전 8문제 다 푸셨으니 쿠폰 기록하겠습니다~ 😉

2021-10-02 02:36 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/17404.cpp
> +        }
이 초기화는 dp 연산이기 때문에 함수로 들어가는게 좋아요~

2021-10-02 02:36 UTC, HyunJiLim0406 commented on 9월 28일 - 동적 계획법/20923.cpp
> +
👍👍👍

2021-10-02 14:35 UTC, merged