[그리디 알고리즘] - 10월 1일
Altu-Bitu/Kimyu pull request #11
Opened 2021-10-03 11:38 UTC by kimyu0218

2021-10-03 11:40 UTC, kimyu0218 commented
5ed736 : 1080번, 1448번, 13305번 풀이 완료했습니다! (16206번 틀렸습니다가 나왔습니다.)

2021-10-04 17:32 UTC, kimyu0218 commented
5ed736c : 1080번, 1448번, 13305번, 16206번 풀이 완료했습니다! (16206번 11줄에 1이 삭제된 상태로 커밋되어  047df89에 수정하여 다시 올렸습니다.)

6ed785b: 8980번의 경우 보내는 마을 오름차순으로 하여 문제를 풀었지만 예제 2번에서 답이 다르게 나왔습니다. 그래서 받는 마을 오름차순으로 하여 문제를 풀고 있는데 더이상 어떻게 해야할 지 모르겠습니다 ㅠㅠ

+) 8980번과 큰 수 만들기 힌트 더 주실 수 있나요?

2021-10-05 05:40 UTC, HyunJiLim0406 requested changes
p2(8980 제외)
수고하셨습니다! 크게 드릴 조언은 없네요~!! 택배 문제 힌트는 코드에 달아놓았습니다.
큰 수 만들기 힌트 드리겠습니다!

일단 저희가 준비한 샘플코드의 시간복잡도는 O(n)입니다. 어떻게 보면 이 문제는 문자 배열을 탐색하며 숫자를 만드는 문제인데 보통 이런 문제들은 시간복잡도가 O(n^2)이 나와요. 저희는 어떤 방법을 사용했길래 O(n)이 나왔을까요?
저희가 지금까지 풀었던 문제들 중에 시간복잡도를 이렇게 줄일 수 있는 방법이 뭐였나요?

그리고 숫자를 '지운다'라는 사실에 집중하면 좋아요!
어떤 경우에 숫자를 지우게 되나요?
정답들의 앞부분을 살펴보시면 어떠한 특징이 있다는걸 알 수 있어요

1234321이 있을 때, 1234보다는 4321이 더 큰 수 예요

수정 후 리뷰어로 저 불러주세요!

2021-10-05 05:40 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/1080.cpp
> +}
오호 저희는 범위를 다르게 해서 뒤집는 연산과 행렬이 제대로 바뀌었는지 확인하는 연산을 분리했는데
이렇게 하면 굳이 분리하지 않아도 되겠네요!

2021-10-05 05:40 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/1448.cpp
> +    for(int i = n-1; i >= 2; i--) {
이건 간단해서 괜찮지만 가끔 인덱스를 실수할 수도 있어요!
저희는 어차피 삼각형의 길이가 가장 긴 경우를 우선으로 탐색할거예요
그럼 정렬조건을 바꾸면 인덱스가 좀 더 간단해지지 않을까요?

2021-10-05 05:40 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/16206.cpp
> +    return cake;
p2
재귀함수는 간단하지만 그만큼 연산시간이 걸린다는 단점이 있어요
그래서 가능하면 꼭 필요할 때만 쓰는게 좋아요
과연 이 함수가 재귀로 구현할 필요가 있는 함수일지 고민해보세요!
간단한 수학적인 고민을 하셔도 좋구요!

2021-10-05 05:40 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/16206.cpp
> +    }
10의 배수인 케이크를 먼저 확인하고 10의 배수가 아닌 케이크를 확인하셨네요! 좋아요~
근데, 이건 한편으론 `10의 배수인 케이크는 10의 배수가 아닌 케이크보다 앞에 와야 한다`라는 정렬 조건이라고 할 수 있지 않을까요?

2021-10-05 05:40 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/8980.cpp
> +int main() {
그리디 문제의 포인트는 현실에선 불가능한 상황을 가정하는거예요!
예를 들어 주요소 문제를 생각해볼까요? 현실적으로 이미 지나온 주유소에서 기름을 받아올 순 없었지만 그렇게 구현했었어요

이 문제도 마찬가지예요! 트럭이 꼭 한방향으로 움직이며 박스를 싣고 내리라는 법은 없어요
이렇게 생각해보면 어떨까요?
각 마을마다 트럭이 한대씩 있어요. 각각의 트럭의 용량은 c구요
트럭에 집중하지 말고 박스가 싣고 내려질 바로 그 곳에 집중해봐요!

그리고 사실 제 힌트는 그냥 코드가 깔끔해지는 방법인데 조금 어려운 방법이기도 해요
그리디 문제는 정렬만 하면 80퍼센트는 해결되는데 이미 80은 하셨네요!
그럼 이건 이제 단순하게 트럭을 이동하는 구현문제가 된거나 다름없어요

2가지의 구현방향을 제시해드렸으니 고민해보세요! 제 힌트가 모호하다면 알려주세요
힌트를 더 드리겠습니다!!

2021-10-05 07:12 UTC, kimyu0218 commented
1448번, 16206번 수정했습니다!! 나머지는 아직 풀고 있어요 :) 근데 16206번 수정했더니 틀렸습니다가 나왔습니다. cmp 함수를 작성해서 10의 배수인 케이크가 먼저 오도록 했습니다. (10의 배수인 케이크 오름차순 + 10의 배수가 아닌 케이크 오름차순) 어디가 잘못된 건지 알 수 있을까요?

2021-10-05 07:23 UTC, kimyu0218 commented
cd49e12 : 1448번 수정했습니다!! 16206번 코드도 업로드 했는데 틀렸습니다가 나와서 다음 커밋에서 수정했습니다.
2342e75 : 16206번 최종본입니다.

2021-10-05 11:15 UTC, HyunJiLim0406 reviewed
p3
수정하신 부분 다 확인했습니다! 케이크 문제 정렬 조건만 좀 더 고민해주세요~

2021-10-05 11:15 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/1448.cpp
> +
앗 제가 내림차순은 어떻게 정렬하는게 좋다고 했었나요?!

2021-10-05 11:15 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/16206.cpp
> +    else if(!(i1%10) && i2%10) return true;
이건 사실 return `!(i1%10)&&(i2%10)`으로 표현할 수 있어요!
다만 그러면 길이조건을 체크할 수 없어서 이렇게 구현하신 것 같아요.
길이를 비교해야하는 경우는 어떤 경우일까요? 예를 들어 12와 34가 있다면 우선순위의 차이가 있을까요?

2021-10-05 11:15 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/16206.cpp
> +    }
👍👍

2021-10-06 00:06 UTC, kimyu0218 commented
1448번, 8980번, 16206번, 큰 수 만들기 수정했습니다!

+) 제가 16206번 코멘트를 제대로 이해한 건지 모르겠어요.. 혹시 말씀하신 게 이게 맞나요?

2021-10-06 02:27 UTC, HyunJiLim0406 reviewed
p2
수고하셨습니다
롤케이크 문제 정렬 조건이 사실 저희가 지금까지 만들어왔던 정렬 조건만큼 직관적이진 않아서 쉽진않아요. 만약 수정이 어려우실 것 같다면 그냥 샘플 코드 나중에 참고하시면 좋아요

수정 후 다시 절 불러주셔도 좋고, 머지하셔도 좋습니다
문제 다 푸셨으니 쿠폰 기록하겠습니다. 만약 지금 머지하신다면 16206이랑 큰 수 만들기는 나중에 샘플 코드 봐주세요!

2021-10-06 02:27 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/16206.cpp
> +}
우리 처음 코드로 돌아가서 생각해볼까요?
10으로 나누어떨어지는 케이크와 나누어떨어지지 않는 케이크로 나누고 각각 길이의 오름차순으로 정렬했어요
그럼 이것에 대한 우선순위는 다음과 같겠네요!
1. 10으로 나누어 떨어질 것
    1-1. 길이가 짧을 것
2. 10으로 나누어 떨어지지 않을 것
    2-1. 길이가 짧을 것

지금 나머지를 비교하셨는데 사실 저흰 나머지를 궁금해할 필요가 없어요
그나저나 왜 둘 다 10으로 나누어 떨어지면 길이가 짧은게 우선순위가 높을까요?
20과 30이 있어요. 1번 자르면 각각 2개, 1개의 케이크가 나올거예요.
그러므로 20이 30보다 우선순위가 높아요

그럼 23과 33은 어떨까요? 1번 자르면 1개씩 2번 자르면 2개씩 나오게 돼요
이런 상황에서 23과 33만 비교했을 때 둘 사이의 우선순위가 존재할까요?

이제 저 위에 미리 써놓은 우선순위 중 하나를 지울 수 있어요
제가 설명을 잘하는 편은 아니라서 그냥 샘플코드 올라오신 뒤에 참고하셔도 좋아요~

2021-10-06 02:27 UTC, HyunJiLim0406 commented on 10월 1일 - 그리디 알고리즘/큰 수 만들기.cpp
> +    for(int i = 0; i < len; i++) {
저희 변수 i를 사용하고 있나요?
그리고 사실 이 문제가 백준에도 똑같이 있는데 백준에 이 풀이를 제출하면 시간초과를 받아요.
이 코드의 아이디어와 어떤 컨테이너를 사용하면 시간복잡도가 O(n)이 돼요

한 번 방법을 고민해보셔도 좋을 것 같아요
물론 이번 과제는 프로그래머스고 프로그래머스에선 맞았습니다를 받으니 굳이 수정할 필요는 없으시구요

2021-10-07 07:41 UTC, merged