[분할 정복] 10월 5일
Altu-Bitu/Kimyu pull request #12
Opened 2021-10-08 09:22 UTC by kimyu0218

[분할 정복] 10월 5일 과제 완료

2021-10-09 04:32 UTC, kimyu0218 commented
f2d3bcd : 필수 과제 풀이 완료했습니다! (1244번, 17281번)
e9c5978: 선택 과제 1802번, 2447번, 16198번, 17829번, 21314번 풀이 완료했습니다.

+) 21314번의 경우 맞았습니다가 나왔는데 코드가 너무 지저분하게 나왔습니다. (k위치를 저장해서 문제를 풀었습니다.) 코드가 이렇게 지저분하게 나오는 거 맞나요...?

+) 1074번의 경우 메모리 초과가 나왔습니다. 벡터를 이용하면 안되는 건가요?

2021-10-09 06:04 UTC, HyunJiLim0406 requested changes
p2(1074 제외)
수고하셨습니다! 다들 잘 구현하셨고 아직 못푸신 1074도 접근은 잘하셔서 금방 해결하시겠네요!
코멘트 몇 개 달아놓았으니 확인해주세요! 대부분은 이런 방법도 있다는 소개(?) 정도긴 해요 이미 코드를 잘 작성해주셨거든요
수정하시거나 힌트가 더 필요하다면 저 불러주세요~

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/1074.cpp
> +int main() {
말씀하신 이유가 맞아요! 벡터를 사용할 수 없는 문제입니다.
문제에서 한 변의 길이가 최대 2^15라고 했는데, 그럼 벡터의 최대 크기가 2^15 * 2^15가 돼요!

지금 풀이는 벡터 전체에 적절한 숫자를 채워주는 풀이잖아요! 근데 사실 저희는 저희가 찾는 위치보다 먼저 빨간선(?)이 지나간 부분이 몇 개인지만 알면돼요

idx를 전역으로 사용하신게 힌트가 될 것 같습니다!

저희가 찾아야 할 (r, c)보다 먼저 탐색하는 원소들은 어떤 원소들일까요? 이 역시 작성해주신 코드에 이미 힌트가 있습니다. 지금 conquer에 걸릴때마다 idx가 4개씩 증가해요. 근데 이건 2*2로 표현할 수 있고, 곧 size예요.

제가 라이브 코딩에서 크기가 다른 각각의 색종이를 만들었었어요. 이번에도 굳이 size==2일 때까지 탐색하실 필요는 없습니다! 물론 엄밀히 말하면 지금 코드의 conquer 부분은 약간의 수정을 거쳐 combine으로 넘어가야해요

그럼 conquer는 어떨 때가 될까요?
아마 제가 의도한 것과 가깝게 구현하신다면 뭔가 잘 안될 수도 있어요. 유정님 스도쿠 문제 처음 푸실 때 있었던 오류 기억나시나요? 그게 힌트가 될 듯합니다

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/1244.cpp
> +    }
아하 이 부분을 재귀함수로 구현하셨네요. 이정도라면 반복문과 연산 차이가 크게 없어서 괜찮겠네요!! 👍

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/16198.cpp
> +        energy -= w[i-1] * w[i+1];
완벽합니다!

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/17281.cpp
> +            temp += baseball(i);
함수 분리 진짜 적절하게 잘하셨습니다 👍

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/17281.cpp
> +
각 베이스의 상태를 bool 배열로 표현하셨네요. 아주 좋은 방법이에요!
근데 예전에 집합문제 기억나시나요? 21개의 숫자를 toggle하고 추가 삭제 했던...
그걸 비트마스킹으로도 풀었었는데 이 문제에도 적용가능합니다! 비트마스킹은 쉬운 내용은 아니라서 고민만 해보셔도 좋아요. 지금 방법도 정말 깔끔하고 좋은 방법입니다!

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/17281.cpp
> +    backtracking(1, n);
엔트리를 짜는데에 백트래킹 함수를 사용해주셨어요
근데 사실 이 문제는 엔트리를 전부 짜고 나서 실제로 야구를 해보고 있기 때문에 중간에 가지치기를 할 수 있는 부분이 없어요! 그니까 백트래킹 함수를 완전탐색을 위한 순열 만들기에 사용하고 있는거예요

저희가 백트래킹 과제에 샘플코드를 2개씩 준비했었는데 이런 문제에 쓰면 좋은 방법이 거기 있었어요
물론 이 방법이 틀렸다는건 아니예요! 이 방법도 자주 사용되는 좋은 풀이입니다.
다만 다양한 방법이 있다는걸 소개해드리는거예요!

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/17829.cpp
> +    }
오 이 방법은 사각형이 압축되는 이미지가 떠오르네요. 저희랑 다른 방법이라 흥미롭네요
저희는 약간 반대 방향으로 구현했습니다! 어떤 방법일지 고민만 해보셔도 좋아요

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/1802.cpp
> +}
종이를 계속 반으로 접는 이미지를 떠올려볼까요? 그럼 불필요한 연산이 하나 보일거예요

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/21314.cpp
> +int main() {
전혀 지저분하지 않은걸요
구현 방법이 약간 다르긴 하지만 저희도 거의 이정도 길이로 구현했어요!
K의 위치를 미리 저장하는건 생각도 못했는데 좋네요!

굳이 리팩토링을 할 부분이 있다면 if문에 continue넣어서 인덴테이션 줄이는 정도일까요?
인덴테이션이나 for문이 깊게 들어간 부분도 없고 불필요한 연산도 딱히 보이지 않습니다! 구현 논리도 명확하구요. 잘 작성하신 코드예요

2021-10-09 06:04 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/2447.cpp
> +    }
p2
이 방법도 나쁘진 않지만 isEmpty를 n^2번 호출하고 있어요
이렇게 되면 중복되는 연산을 몇 번 하기도 할거예요
지금 9등분으로 나누고 가운데 부분을 지우는 것 까진 아주 잘 구현하셨어요! 대신 재귀함수 호출을 딱 한 번해서 별을 입력하는 방법으로 구현하면 어떨까요?

힌트를 드리자면 그 함수의 기저조건은 size가 1일수도 3일수도 있는데 3인 경우로 구현하시고 나면 1도 된다는걸 깨달으실거예요

2021-10-10 08:49 UTC, kimyu0218 commented
1074번, 1802번 수정했습니다!

+) 1074번은 (r,c)에 도달했을 때 답을 리턴하는 방법을 못찾아서 result 전역 변수에 답을 담았습니다. 이렇게 하는 것이 맞나요?
 
+) 1802번의 경우 right 부분을 검사하는 부분을 제거했습니다. while문에서 양쪽이 다른지 확인했기 때문에 따로 검사할 필요가 없는 게 맞을까요?

2021-10-10 13:25 UTC, HyunJiLim0406 approved these changes
p3
수고하셨습니다! 질문주신 코드는 어떤 내용인지 제가 약간 이해하기가 어려워서 도움을 드리기 어렵네요...! 주석이 있다면 제가 도움을 드릴 수 있습니다
근데 그 문제가 리턴형이 따로 있기가 쉽지 않은 문제긴 해요! 저희도 void 리턴입니다

풀어주신 문제 머지하서도 좋구요. 다 푸셨으니 쿠폰도 기록하겠습니다!
질문 주신 부분이나 기타 더 궁금한 점이 있다면 저 불러주세요!!

2021-10-10 13:25 UTC, HyunJiLim0406 commented on 10월 5일 - 분할 정복/1802.cpp
> +    divide(left, l-1, paper); // left ~ mid����� �˻�
맞아요! 절반만 확인해도 돼요

2021-10-11 05:43 UTC, merged