[이분 탐색] 10월 8일
Altu-Bitu/Kimyu pull request #13
Opened 2021-10-11 08:33 UTC by kimyu0218

16401번, 19637번 풀이 완료했습니다! 

+) 2343번의 경우 틀렸습니다가 나왔고, 3079번은 시간 초과가 나왔습니다. 2343번은 어디가 틀렸는지 못찾고 있습니다ㅠㅠ

2021-10-11 08:45 UTC, kimyu0218 commented
+) 2343번 어디가 틀렸는지 알 수 있을까요? 16401번과 거의 동일하게 알고리즘을 짰고 출력 결과도 올바르게 나옵니다..! left는 강의 길이보다 길어야 해서 lecture[n-1]으로 설정했고, right는 n개의 강의가 있으므로 lecture[n-1]*n으로 설정했습니다.

+) 3074번은 시간 초과가 나왔습니다. (우선 순위 큐를 이용하여 풀었습니다..!) 그래서 sec을 하나씩 증가하지 않도록 만들었는데도 계속 시간 초과과 나옵니다.  ( 73ea0cf ) 큐를 사용하면 안되는 건가요?

나머지 문제들은 나중에 풀어서 다시 커밋하도록 하겠습니다!! 천천히 리뷰 주세요ㅎㅎ 항상 세세하게 리뷰 해주시고 힌트 주셔서 감사합니다!!

2021-10-12 08:36 UTC, kimyu0218 commented
9437bbe : 13397번, 징검다리 건너기 문제 풀이 완료했습니다!

+) 아래 커밋들은 주석 수정하고 잘못 올라간 파일을 지운 것입니다. 무시해주세요..!

2021-10-13 03:01 UTC, HyunJiLim0406 reviewed
p3(2343, 3079 제외)
수고하셨습니다! 2343번은 놓치신 조건이 하나 있네요. 그것말고는 문제 없으니 금방 고치실거예요
3079번과 관련한 코멘트도 달아놓았으니 확인해주세요~!
그리고 다른 문제들도 소소하게 최적화할 수 있는 부분 적어놓았습니다

수정하시거나, 또 질문이 있으시면 리뷰어로 저 불러주세요!

2021-10-13 03:01 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/13397.cpp
> +    cout << findMin(0, max_num, m);
구간 점수 최댓값의 최댓값(ㅎㅎ 말이 어렵네요...)이 정말 max_num이 맞을까요?
물론 이렇게 제출해도 맞았습니다를 받고, 큰 문제는 없지만 정확한 right는 어떻게 될까요?

2021-10-13 03:01 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/16401.cpp
> +}
정렬을 했다는걸 생각하면 여기서 소소하게 연산을 줄일 수 있는 방법이 하나 있어요!
len값이 특정 과자의 길이보다 길 수도 있으니..?

2021-10-13 03:01 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/19637.cpp
> +        if(grade.find(power) != grade.end()) continue;
이 방법도 있지만, map에서 value가 int형일 때, value의 초기값은 0이었어요!
string은 어떨까요? 그걸 활용한다면 find말고 어떤걸 사용할 수 있나요?

2021-10-13 03:01 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/2343.cpp
> +int main() {
'블루레이를 녹화할 때, 강의의 순서가 바뀌면 안 된다.'라는 조건이 있네요!

2021-10-13 03:01 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/3079.cpp
> +int main() {
네! 입력이 꽤 크네요! 우선순위 큐의 시간복잡도로는 시간안에 풀 수 없어요
걸리는 시간의 '최솟값'을 구하고 있네요. 만약 모든 사람이 심사를 30초만에 받을 수 있었다면 30초 이상의 시간에도 당연히 심사를 받을 수 있어요!

2021-10-13 03:01 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/징검다리 건너기.cpp
> +bool pass(vector<int> stones, int k, int p) {
사실 대부분의 parametric search문제에 대해 이렇게 bool로 선언하고 가망없는 mid값에 대해 중간에 return false를 해주면 연산속도가 조금 더 빨라지는 장점이 있어요!
저흰 그냥 배열의 원소가 정렬된 상태란걸 보여주기 위해 int리턴형을 사용한거구요. 좋네요!!

2021-10-13 12:02 UTC, kimyu0218 commented
2343번, 13397번, 16401번, 19367번 수정했습니다!!

+) 3079번 이분 탐색으로 푸는데 5% 정도에서 틀렸습니다가 나옵니다 ㅠㅠ 최소 시간은 t[0], 최대 시간은 t[n-1]*m으로 설정했습니다. (m이 1이상이기 때문에 t[0]만큼 무조건 기다리게 된다고 생각했어요..!) 어디가 잘못된 건가요?

이분 탐색에서 비슷한 문제로 오류가 나는 것 같은데 어디가 잘못된 건지 잘 못찾겠네요ㅠㅠ

2021-10-13 12:41 UTC, HyunJiLim0406 requested changes
p3(3079 제외)
잘 수정해주셨네요! 3079번은 정말 큰 문제가 아닙니다
이런 이분 탐색 문제를 풀 때 문제가 안풀린다면 한 80%는 left, right 문제고 19%는 특정 mid에 대한 연산을 하는 부분이라고 생각해요. 그렇기 때문에 관련 문제를 많이 풀어볼수록 경험치가 금방 쌓이는 주제기도 해요!
이건 1%네요 하핳
수정하시고 리뷰어로 저 불러주세요!

2021-10-13 12:41 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/13397.cpp
> +    cout << findMin(0, max_num-min_num, m);
👍

2021-10-13 12:41 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/16401.cpp
> +    }
continue는 사실 이 경우엔 연산에 큰 영향을 미치지 않아요!
break를 쓸 수 있는 방법은 없을까요?

2021-10-13 12:41 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/19637.cpp
> +        grade[power] = g;
👍
사실 clion에서 이렇게 작성하면 ide가 `!grade[power].empty()`로 수정해줄거예요. 이걸 알려드리려고 "" 얘기를 했던거였어요

2021-10-13 12:41 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/3079.cpp
> +        cnt += (mid / t[i]);
오 여기서 return 하는 방법은 생각도 못했어요 👍

2021-10-13 12:41 UTC, HyunJiLim0406 commented on 10월 8일 - 이분 탐색/3079.cpp
> +typedef long long ll;
논리적인 문제는 전혀 없어요!
알고리즘 문제를 풀면서 가장 흔하게 발생하는 실수 중 하나를 하셨네요!
int끼리 연산하면 결과를 담을 변수가 long long이어도 중간에 오버플로우가 발생할 수 있어요
어딜 빠뜨렸는지 확인해볼까요?

2021-10-13 14:22 UTC, kimyu0218 commented
16401번, 3079번 수정했습니다!! 천천히 리뷰 해주세요 ㅎㅎ

2021-10-14 03:42 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 다 잘 수정하셨네요~!
이제 머지하셔도 좋습니다. 쿠폰 기록해둘게요!

2021-10-14 04:25 UTC, merged