[투 포인터] 10월 11일
Altu-Bitu/Kimyu pull request #14
Opened 2021-10-15 08:07 UTC by kimyu0218

1253번, 2473번, 2531번, 2607번, 13422번, 20922번 풀이 완료했습니다.

2021-10-15 08:10 UTC, kimyu0218 commented
+) 14500번:  아예 어떻게 풀어야할지 감을 못잡겠어요ㅠㅠ

+) 2143번: 9%에서 틀렸습니다가 나왔습니다..! 구간합이라서 따로 정렬을 진행하지 않았습니다. a 배열 부분합을 구하고 b배열 부분합을 구해서 부 배열 쌍을 만족하는지 검사하도록 했습니다. 어디가 잘못된 건지 알 수 있을까요?

시험 기간이니까 천천히 리뷰해주셔도 괜찮아요!!

2021-10-15 13:30 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 그냥...공부하기 싫어서 온거니까 천천히 확인해주셔도 괜찮아요 하핳
2143번 틀린 이유는 코드에 달아놓았구요. 구현 방법에 대해 몇가지 궁금한 것도 있어서 그거에 대한 질문도 적어놓았어요!

그리고 14500번 추가 힌트 드리겠습니다!
일단 블럭의 모양이 너무 다양해서 이걸 하나하나 구현하는건 힘들거예요
마침 오늘 dfs, bfs를 배웠으니 그거와 관련한 힌트로 드릴게요! (이 문제가 dfs, bfs인건 아니예요!)

오늘 2차원 배열에서 탐색하는걸 많이 봤었어요. 근데 dfs로 탐색했던 방법들의 특징을 아시나요?
깊게 들어가는 하나하나의 경로에 대해서 한붓그리기가 가능해요.
달리 말하면 한 붓 그리기가 가능한 경로는 dfs 또는 이 문제에 사용하는 알고리즘으로 탐색할 수 있다는거예요! dfs는 어떤 알고리즘과 비슷할까요?

이제 다시 저희가 리드미에 드렸던 힌트를 보시면 어떤 말인지 감이 오실까요?
그리고 이 문제의 입력이 크지 않아서 하나하나의 칸에 대해 가능한 모든 블럭을 찾아도 시간안에 들어와요!

수정하시거나 추가 힌트가 필요하시다면 저 불러주세요!

2021-10-15 13:30 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/1253.cpp
> +        }
이건 개인적인 취향에 가까울 수도 있는데 이 부분이 투 포인터 알고리즘이잖아요!
그래서 여길 함수로 빼는 것도 나쁘지 않아요
break는 사실 달리보면 return이라고 볼 수도 있거든요

2021-10-15 13:30 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2143.cpp
> +int main() {
문제의 조건에 함정이 있어요! 각 배열의 원소는 `'절댓값'이 1,000,000을 넘지 않는 정수이다`
누적합의 값이 증가한다는 보장이 없겠네요!

그리고 이 방식도 굉장히 좋은 접근인데요. a의 특정 부배열에 대해 매번 O(n)의 시간복잡도로 가능한 b의 부배열을 찾고 있어요! 만약 a의 부배열 값이 k인데 저번에도 k인 부배열이 있었다면, 한 번 b 배열에 대한 연산을 했음에도 불구하고 다시 같은 연산을 해야해요
n과 m의 크기가 1,000이네요. 가능한 모든 부배열을 구해도 시간 안에 들어올거예요!

2021-10-15 13:30 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2473.cpp
> +}liquid;
혹시 3 크기의 배열이나 벡터를 사용하지 않고 구조체로 묶어주신 이유가 있을까요?

2021-10-15 13:30 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2473.cpp
> +            if(right == i) { right--; continue; }
용액 하나를 고정하는 아이디어를 떠올리셨네요! 근데, 이 부분을 없앨 수 있는 방법이 있어요!
1 2 3 4 5 번 용액이 있다고 할게요
1번 용액을 고정하고 1 2 3번 용액을 섞는건
2번 용액을 고정하고 1 2 3번 용액을 섞는 것과 같아요

어떻게하면 이런 중복되는 연산을 없앨 수 있을까요?
1번 용액이 들어가는 모든 경우의 수는 처음에 1번 용액을 고정할 때 이미 다 고려했어요!

2021-10-15 13:30 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2531.cpp
> +    }
p1
모든 경우의 벨트에 대해서 먹게되는 초밥을 하나하나 계산하고 있네요!
이건 시간복잡도 O(n^2)이며, 벨트의 이동에 따라 중복되는 초밥을 활용할 수 없어요
혹시 쿠폰으로 주어지는 초밥을 관리하기가 어려워서 이렇게 구현하신걸까요?
그럼 쿠폰 초밥을 먼저 준다고 생각하면 어떨까요?

2021-10-15 13:30 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/13422.cpp
> +
👍

2021-10-15 13:30 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/20922.cpp
> +        }
오 생각 못했던 방법인데 좋네요!

2021-10-15 13:30 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2607.cpp
> +}
이 함수가 단어 구성 결과를 리턴해도 좋겠네요!

2021-10-15 13:30 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2607.cpp
> +        idx = i;
이 부분이 잘 이해되지 않는데 혹시 추가 설명 해주실 수 있을까요!
그리고 line 15~16은 합칠 수 있지 않을까요? 어떻게 보면 abs(alpha[i] - cmp[i])의 값이 different에 추가되는 값이기도 하니까요!

2021-10-16 14:45 UTC, kimyu0218 commented
a750263 : 1253번, 2473번, 2531번 수정했습니다!
ddac81d : 2607번 주석 추가했습니다..! 주석을 달긴 달았는데 설명을 잘 못드리겠어요ㅠㅠ 이해 안가시면 다시 말씀해주세요!

2021-10-17 07:45 UTC, HyunJiLim0406 requested changes
p2 (못 푼 문제 제외)
수고하셨습니다! 수정해주신 문제들 다 확인했습니다
문제 더 푸시거나, 수정하시거나, 질문이 있으시면 편하게 불러주세요!

2021-10-17 07:45 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/1253.cpp
> +int twoPointer(int i, int n) {
a[i]는 좋은수거나, 아니거나 둘 중 하나겠네요!
bool은 int로 자동 형변환이 되기도 하니 리턴형을 bool로 해도 괜찮아요!

2021-10-17 07:45 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2473.cpp
> +
👍

2021-10-17 07:45 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2473.cpp
> +                liquid[2] = l[right];
i, left, right 순서로 저장하면 마지막에 정렬할 필요가 없겠네요!

2021-10-17 07:45 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2473.cpp
> +void threeLiquid(int n) {
liquid를 벡터로 해서 vector<int>를 리턴할 수도 있어요!

2021-10-17 07:45 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2531.cpp
> +
별건 아니지만 상수 변수의 이름은 어떤 것을 의미하는지가 명확하게 드러나는게 좋아요!
이건 초밥의 최대 종류라는 뜻이니까 MAX_KIND..? 이것보단 좋은 이름이 많을 것 같은데 이런 류의 이름으로 바꾸면 좋아요!

2021-10-17 07:45 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2531.cpp
> +        left = (left + 1) % n;
이 조건은 while문에 들어갈 수도 있겠네요!
근데 그럼 right의 초기값이 k인게 문제긴 해요...
종료조건에 걸려도 최소한 한번은 실행해보던 while문은 어떤 것이었을까요?

2021-10-17 07:45 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2607.cpp
> +        idx = i;
아하! 이해했습니다! 제가 헷갈렸던 부분은 2번째 조건이었거든요.
근데 알파벳 26개에 대해 different를 전부 계산했다고 생각해볼까요?
2번 조건에 들어올 수 있는 경우에 different의 값은 어떻게 될까요? different 말고 어떤걸 고려하면 좋을까요?
abc acd 와 같은 경우를 잘 생각해보세요!

매번 if문으로 각 조건의 위반 여부를 확인할 필요없이 최종 different와 연산 없이 이미 알고 있는 정보로 규칙 위반 여부를 알 수 있어요!

2021-10-17 16:11 UTC, kimyu0218 commented
5e22c6a : 2473번 수정했습니다!
d8df33b : 1253번, 2143번, 2531번 수정했습니다!

+) 나머지 문제들도 차근차근 수정하겠습니다 :)

2021-10-18 09:35 UTC, HyunJiLim0406 requested changes
p3 (수정된 문제)
수정해주신 문제들은 완벽하네요!
문제 더 푸시거나 질문 있으시면 불러주세요~

2021-10-20 14:16 UTC, kimyu0218 commented
2531번, 14500번 올립니다..! 2531번은 예제는 맞게 나오는데 틀렸다고 나옵니다ㅠㅠ 14500번은 예제 3번 답이 틀리게 나옵니다.

+) 2531번은 다른 문자가 나올 때까지 left를 증가시켰습니다. 그리고 different를 계산해서 비슷한 단어 여부를 평가했습니다. 다음으로 다른 문자가 나올 때까지 right를 감소시켰습니다. left처럼 different 여부를 평가하고 left와 right 문자를 바꿀 수 있는지 확인했습니다.

+) 14500번은 힌트 주신 대로 dfs를 적용했습니다. 이 문제가 dfs로 푸는 게 아니라고 하셨는데 예제 3번 때문에 사용하지 못하는 건가요?

2021-10-21 03:37 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 비슷한 단어라고 하신거보면 2607번을 의미하신거겠죠?
풀어주신 두 문제 모두에 대한 코멘트 남겨놓았습니다. 거의 다 푸신 것 같네요!
수정하시거나 질문이 있으시면 저 불러주세요~~

2021-10-21 03:37 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/2607.cpp
> +bool checkConfiguration(int cmp[26]) { // �� ���� ���� ���ϱ�
이거 예전 풀이가 맞아요!!
제가 드렸던 조언은 각 단어의 alpha 배열의 차이값을 계산한 different 변수 하나로 비슷한 단어 여부를 체크할 수 있단 거였고, 거기서 약간 리팩토링 할 수 있는 부분이 있다는 뜻이었어요!

만약에 어떤 문자 하나를 지우거나 더해서 다른 단어와 구성이 같으려면 어떤 상태여야 할까요? 아마 두 단어의 길이가 1차이일거예요. 근데 사실 이건 고려햐지 않아도 돼요. diff가 1이란 뜻은 결국 길이 차이가 1이라는 뜻이니까요

그럼 문자를 바꿔야하는 경우는 어떨까요? 두 단어의 최종 diff값이 어떻게 나올까요? 두 단어의 길이 차이는 어떻게 나오나요?

2021-10-21 03:37 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/14500.cpp
> +int main() {
dfs와 백트래킹의 차이가 굉장히 모호한 편인데요
이론적인 설명을 하면 재미도 없고 이해도 어려우니 직관적으로 설명하면
방문 여부를 취소하면 백트래킹, 아니라면 dfs입니다!

저희 dfs 구현할 때 방문 여부를 딱히 철회하거나 하진 않았어요. 백트래킹의 핵심은 다시 방문하기 위해 방문을 취소하는거라고 했었구요.
지금 구현에 의하면 이건 백트래킹이겠네요!

지금 코드 완벽한데 하나 빠진게 있어요
백트래킹으로 구할 수 없는 블럭이 하나 있어요. 백트래킹으로 탐색 가능한 블럭은 하나의 시작 블럭에서 3번 이동한거예요. 손가락으로 한 번 각각의 블럭들을 그려보세요. 그려지지 않는 블럭이 하나 있을거예요
그건 어쩔 수 없이 따로 브루트포스로 구해줘야 합니다!

2021-10-21 03:37 UTC, HyunJiLim0406 commented on 10월 11일 - 투 포인터/14500.cpp
> +int findMax() {
어차피 max_num은 전역변수기 때문에 이걸 리턴한다는건 의미없는 일이에요!
이럴땐 그냥 void로 하셔도 괜찮아요

2021-10-31 02:34 UTC, kimyu0218 commented
14500번 수정했습니다!! 2607번의 경우 원래 코드로 수정했습니다 (리팩토링 방법은 아직 고민 중입니다)

2021-10-31 08:34 UTC, HyunJiLim0406 approved these changes
p2
수고하셨습니다 2607번은 간단한 리팩토링만 샘플코드 참고해주세요
사실 14500번도 백트래킹 부분 잘 구현하시긴 했지만 핑크색 블록을 하드코딩으로 처리하고 있네요. 제가 드린 힌트로 좀 더 고민해보시고 수정하셔도 좋고 남은 과제가 많으니 그냥 나중에 샘플코드 참고하셔도 좋습니다!
일단 8문제 다 푸신걸로 기록하고 쿠폰도 기록하겠습니다
머지하셔도 좋고 수정하시고 저 불러주셔도 좋아요~!

2021-10-31 08:34 UTC, HyunJiLim0406 commented on 10월 12일 - 투 포인터/14500.cpp
> +    int dx[4] = {0, 0, -1, 1}, dy[4] = {-1, 1, 0, 0}; // �� �� �� ��
이런 재귀함수에선 같은 dx, dy가 매번 초기화되니까 그냥 전역으로 빼는 것도 좋아요!

2021-10-31 08:34 UTC, HyunJiLim0406 commented on 10월 12일 - 투 포인터/14500.cpp
> +void checkPink(int row, int col, int first) { // ��ũ�� ��� ��� Ȯ��
p2
실수없이 잘 구현하셨지만 하드코딩이네요! 아주 간단하게 생각해볼 수 있어요
가운데를 기준으로 ㅜㅏㅗㅓ 모양을 겹쳐보면 어떤 모양이 되나요?

2021-10-31 09:50 UTC, merged