[맵과 셋]9월 7일
Altu-Bitu/Kimyu pull request #4
Opened 2021-09-11 16:54 UTC by kimyu0218

2015번과 18870에서 시간 초과가 발생했습니다.
힌트 조금만 더 주실 수 있나요?

2015번의 경우 다음과 같이 2개의 포인터를 이용해서 시도해봤는데 틀렸다고 나옵니다.

int partialSum(int k, int n) {
    int front = 0, rear = 0, result = 0;
    long long sum = 0;

    sum = a[rear];
    while(front <= rear && rear < n) {
        if(sum > k) sum += a[++rear];
        else if(sum == k) {
            result++;
            temp.insert(rear);
            sum -= a[front++];
            ++rear;
        }
        else sum -= a[front++];
    }

    for(int iter : temp)
        result++;

    return result;
}
이 코드를 응용할 수는 없을까요?

2021-09-12 04:33 UTC, HyunJiLim0406 requested changes
p3(2015, 18870 제외)

코드를 아주 잘 짜주셔서 따로 코멘트 드릴 부분이 크게 없었어요!
18870번과 관련된 코멘트는 코드에 달았구요

2015번에 대해서는...지금 투포인터를 응용하셔서 문제를 푸신 것 같아요!
근데 투포인터로 문제를 풀려면 문제가 몇 가지 조건을 충족해야하는데 이 문제는 그렇지 않아요.
해당 코드를 응용할 순 없고, 새로운 풀이를 찾으셔야합니다!

2021-09-12 04:33 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/10757.cpp
> +void addLargeNum(const string &a, const string &b) { // ���ϱ�
merge sort 구현할 때와 비슷한 논리로 아주 잘 푸셨습니다!
그리고 스택도 사용하셨네요!! 멋져요~ 👍👍👍

2021-09-12 04:33 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/14425.cpp
> +        s.insert(input);
scanf도 좋지만 c++이니까 cin을 사용하면 좋을 것 같아요!

2021-09-12 04:33 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/1764.cpp
> +        nonListen.insert(input);
여기도 cin 사용해주세요!

2021-09-12 04:33 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/18870.cpp
> +    }
이 부분의 시간복잡도가 O(n^2)이라 그래요!
셋을 하나하나 순회하며 값을 찾는건 시간이 너무 오래걸려요. O(nlogn)까지 줄여야 해요!

2021-09-12 04:33 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/19636.cpp
> +        }
함수 안에서 출력을 하는건 좋지 않아요!

2021-09-12 04:33 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/9375.cpp
> +            else kinds[kind]++;
맵과 셋 ppt `이것도 알아보세요` 부분을 보시겠어요?

2021-09-12 09:53 UTC, kimyu0218 commented
1764, 2015, 9375, 14425, 18870, 19636번 수정했습니다.
18870의 경우 여전히 시간 초과가 납니다ㅠㅠㅠ
O(n log n)은 아니지만 다른 방법을 이용해서 O(n^2)은 아닌 것 같은데 여전히 시간 초과가 나는 것 같아요..
혹시 제가 다시 짠 코드도 O(n^2)인 건가요?

그리고 다른 파일이 업로드 되어서 삭제했습니다..!

2021-09-13 04:32 UTC, HyunJiLim0406 reviewed
p3(18870번 제외)

18870번 부분마다 시간복잡도 적어놓았습니다!
이 문제는 O(nlogn)인 로직이 최대 2개까지만 들어갈 수 있어요! 지금은 3개가 들어있어서 시간초과가 발생하는거구요
셋으로 푸는게 어려우시다면 벡터로만 풀어보는건 어떨까요? 이 문제에 대해 저희가 준비한 풀이는 셋을 사용한 버전과 벡터만 사용한 버전 총 2개입니다!

그리고 [15552번](https://www.acmicpc.net/problem/15552) 여기도 들어가보시면 도움이 될 것 같아요!

2021-09-13 04:32 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/18870.cpp
> +        v.push_back({tmp, i}); // ��ǥ�� �Է� �� ����
O(nlogn)

2021-09-13 04:32 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/18870.cpp
> +        m.insert({*iter, idx++});
O(nlogn)

2021-09-13 04:32 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/18870.cpp
> +        cout << m[iter->first] << ' ';
O(nlogn)

2021-09-13 04:32 UTC, HyunJiLim0406 commented on 9월 7일 - 맵과 셋/9375.cpp
> +            kinds[kind]++;
👍

2021-09-13 12:06 UTC, kimyu0218 commented
18870번 수정했습니다!!

+) 제가 git 사용이 미숙해서 18870번만 올렸는데 여러 파일이 같이 올라갔어요. 18870번만 확인하시면 될 것 같습니다...! git status하니까 9월 10일 과제 목록들도 같이 보이는 것 같아요. 우선 commit하고 삭제했는데 나중에 9월 10일 과제 목록이 commit이 될지 잘 모르겠어요ㅠㅠ 답변 감사합니다

2021-09-13 12:15 UTC, HyunJiLim0406 reviewed
p3
lower bound 함수를 찾아내셨네요!
벡터를 정렬해서 중복제거하는 지금의 방법도 좋지만, 셋에 넣은 뒤 벡터에 옮기는 방법도 있어요!
아무튼 이제 머지해도 될 것 같습니다!
아마 파일은 푸시한게 아니라면 다시 올릴 수 있을 것 같아요

2021-09-13 14:10 UTC, merged