[브루트 포스] 9월 21일
Altu-Bitu/Kimyu pull request #8
Opened 2021-09-23 14:19 UTC by kimyu0218

2108번, 2503번, 2858번, 3077번, 10448번, 20055번 풀이 완료했습니다!
+) 1107번과 14501번의 경우 오류가 납니다. 어디가 잘못된 건지 알 수 있을 까요?

2021-09-23 14:20 UTC, kimyu0218 commented
1107번의 경우 예제 중 하나에서 답이 다르게 나옵니다. 14501번은 예제는 올바르게 나오는데 틀렸다고 나옵니다..! (14501번은 재귀를 이용해서 풀었습니다.)

2021-09-23 16:04 UTC, HyunJiLim0406 requested changes
p2(1107, 14501 제외)
먼저 늦은 시간에 죄송합니다. 제가 내일은 리뷰를 볼 시간이 없을 것 같은데 안풀리는 문제가 있으시다고 하셔서 급하게 했어요 😥
일단 안풀린다고 하신 문제들 빼곤 다 너무 잘 풀어주셨어요! 함수화도 적절한 곳에서 잘 하셨고, 효율성도 크게 문제되는 부분은 없네요!

질문주신 문제들 틀린 이유는 코드에 적어놓았습니다. 14501번은 정말 어려웠어요 😁
수정 후 리뷰어로 저 호출해주세요~!

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/10448.cpp
> +int eureka(int num) { // �ش� �ڿ��� 3���� �ﰢ���� ����� ǥ��Ǵ°�
이 함수는 표현 가능한가/아닌가로 나눌 수 있으니까 bool 자료형이면 좋겠네요!

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/1107.cpp
> +const int MAX_CHANNEL = 500000;
최대 채널이 정말 50만일까요?
목표 채널이 500000인데, 멀쩡한 버튼이 0, 5, 1밖에 없어요. 그렇다면..?

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/1107.cpp
> +
n이 채널보다 작으면 어떻게 되나요!

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/1107.cpp
> +            else temp = i-n + to_string(i).length();
여기는 그냥 abs로 처리하면 좋아요!

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/14501.cpp
> +    p.assign(n, 0);
이건 함께 엮이는(?) 데이터니까 pair 또는 구조체로 묶는게 좋아요~

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/14501.cpp
> +}
*와! 이거 좀 어려웠네요!! 발견했습니다!
line 8에 문제가 있어요! 두번째 조건을 보면 이 날에 상담을 하지 못하면 바로 return 0을 해버리네요
근데 이 날 상담을 하지 못하면 이 이후의 수익이 0원일까요?

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/20055.cpp
> +}
p2
회전을 직접 구현하셨네요! 근데 이것보다 효율적인 방법이 있어요
회전을 하게 되면 올리는 위치와 내리는 위치가 바뀌게 되네요?

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2108.cpp
> +    }
입력하면서 처리하는 부분 완벽하네요!

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2108.cpp
> +        if(max == cnt[i] && max_cnt == 2) result = i - 4000;
1개인 경우와 2개인 경우 잘 처리하셨네요!

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2503.cpp
> +}
이렇게 전처리를 하는 것도 나쁘지 않은 방법이지만 그냥 반복문을 돌면서 그때그때 valid 체크를 해주는게 메모리면에선 더 좋아요!
그리고 line 23에서 continue를 해주니까 line 25가 else if일 필요는 없겠네요!

2021-09-23 16:04 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/2503.cpp
> +            if(strike != strike_cnt || ball != ball_cnt) suppose[i] = false; // ���� ���� ����Ʈ���� ���
아하 이렇게 구현하신다면 setInvalid() 함수가 있어도 괜찮네요!

2021-09-24 06:44 UTC, kimyu0218 commented
1107번, 2503번, 10448번, 14501번, 20055번 수정했습니다!! 한가하실 때 리뷰 주세요ㅎㅎ

2021-09-25 10:19 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 전부 잘 수정하셨네요~
사소한 피드백이 딱 하나 있는데, 보시면 아시겠지만 아주 간단한거라서요...!
간단하게 수정하고 바로 머지하셔도 좋아요!
8문제 다 푸셨으니 쿠폰 기록해둘게요~ 😁

2021-09-25 10:19 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/1107.cpp
> +    for(int i = 0; i <= 2 * MAX_CHANNEL; i++) {
좋아요!

2021-09-25 10:19 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/14501.cpp
> +}
여기는 삼항연산자 말고 더 간단한걸 쓸 수 있겠네요!
지금 코드는 a와 b중에 더 큰걸 리턴하는데 그렇다면 뭘 쓸 수 있을까요?

2021-09-25 10:19 UTC, HyunJiLim0406 commented on 9월 21일 - 브루트 포스/20055.cpp
> +}
👍

2021-09-25 11:42 UTC, merged