[백트래킹] 9월 24일
Altu-Bitu/Kimyu pull request #9
Opened 2021-09-27 10:17 UTC by kimyu0218

2021-09-27 10:21 UTC, kimyu0218 commented
+) 1759번은 7% 정도에서 틀렸다고 나오는데 어디서 틀렸는지 못찾겠습니다ㅠㅠ 2580번은 81번까지 도달할 줄 알았는데 14번째 쯤에서 backtracking이 멈추는 것 같습니다..!

2021-09-27 12:48 UTC, HyunJiLim0406 requested changes
p3(1759, 2580 제외)
수고하셨습니다! 완벽하네요!
제가 드린 코멘트들은 그냥 더 생각해보면 좋은 것들이지 리팩토링이 필요하단건 아니에요
이미 코드를 너무 잘 짜주셨거든요

질문주신 문제들이 틀린 이유는 코멘트로 달아놓았어요
아주 큰 문제들은 아닌듯하네요!

수정하고 저 호출해주세요~

2021-09-27 12:48 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/10971.cpp
> +    check[start] = true; // visited
사실 start에 대한 true 처리는 한번만 해도 괜찮잖아요...!
그래서 이건 메인해서 해도 돼요. 대신 start에 대한 false처리도 메인에서 해야하구요

2021-09-27 12:48 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/10971.cpp
> +int main() {
백트래킹으로 아주 잘 푸셨습니다!
이 문제는 next_permutation을 이용한 완전탐색 풀이도 있는데 어떤 방법일지 생각해봐도 좋아요

2021-09-27 12:48 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/15661.cpp
> +    if(idx >= n) { // ���� ���: idx ���� ��� ����
idx가 n보다 커질일은 없을 것 같아요!

2021-09-27 12:48 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/15661.cpp
> +        }
능력치를 계산하는 이 부분을 함수로 뺄 수도 있어요!

2021-09-27 12:48 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/15661.cpp
> +int main() {
잘 푸셨어요! 제 생각엔 {0, 1, 0, 1}과 {1, 0, 1, 0}이 다른 경우로 취급될 것 같은데 맞나요? (아니라면 죄송합니다)
이 두 경우의 힘의 차이는 동일해서 이렇게 대칭되는 경우는 가지치기하면 좋아요!
이건 쉽지 않은 방법이라서 생각만 해보세요

2021-09-27 12:48 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/1759.cpp
> +int main() {
*오호 유정님이 가져오시는 오류는 항상 뭔가 재미있네요!
음 이번 오류는 직접 찾는게 좋을 것 같아요! 힌트를 드리자면 하나는 출력에서 문제가 있었고, 하나는 인덱스에서 문제가 있었어요.
제가 이렇게 알려드리는 이유는 논리에는 문제가 없지만 아주아주 사소한 오류기 때문입니다!
힌트를 하나 더 드리자면 아무 입력이나 알파벳 순서를 섞어서 넣어보세요!

2021-09-27 12:48 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/2529.cpp
> +            else backtracking(cnt+1, 0, i-1);               // �ε�ȣ�� >�� ���: ��� ���ڸ� Ž��
이 방법은 생각못했는데 좋은 방법이네요!

2021-09-27 12:48 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/2529.cpp
> +int main() {
지금 풀이도 아주 좋지만 출력값들을 살펴볼까요?
최솟값과 최댓값을 이루는 숫자들에는 어떠한 규칙(?) 같은게 있어요!
이것도 생각만 해보셔도 좋아요. 지금 풀이도 이미 완벽하거든요

2021-09-27 12:48 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/2580.cpp
> +int main() {
*오류가 2개 있네요! 하나는 알고나면 허무하실 오류고, 다른 하나는 제가 힌트를 드릴게요
14에서 프로그램이 끝난다고 하셨는데 아주 잘 찾아내셨어요. 프로그램이 끝난다는건 더이상 가능한 답이 없다는건데...도대체 check 배열들이 어떤 상태길래 가능한 답이 없다고 하는걸까요? 이걸 출력해보시면 허무한 오류를 잡아내실 수 있구요
음 만약에 가능한 스도쿠 답이 여러개라면 어떻게 될까요?

2021-09-28 08:17 UTC, kimyu0218 commented
1759번, 2580번, 10971번, 15661번 수정했습니다!!

1759번의 오류는 찾아서 수정했는데 2580번은 모르겠어서 다른 방법으로 풀었어요...!

2021-09-28 08:57 UTC, HyunJiLim0406 approved these changes
p2
수고하셨습니다! 근데 2580번이 기존 풀이보다 비효율적인 방법이 됐어요...!
진짜 사소한 실수였고, 힌트를 더 드렸으니까 다시 한 번 찾아봐요!
수정 후 리뷰어로 저 호출해주세요~

2021-09-28 08:57 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/15661.cpp
> +void computeSkillScore() { // �ɷ�ġ ���
이 함수는 두 팀의 힘 차이만 리턴하게 하고 갱신은 백트래킹 함수에서 하는게 좋아요!

2021-09-28 08:57 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/1759.cpp
> +
👍 정확히 하면 alphabet[0]에는 아무 값이 없으니 alphabet+1 부터 정렬하는게 좋아요

2021-09-28 08:57 UTC, HyunJiLim0406 commented on 9월 24일 - 백트래킹/2580.cpp
> +int main() {
p2
공백을 저장하는 이 풀이는 기존 풀이보다 비효율적이라 좋지 않아요!
complete 변수를 사용해야 하는건 잘 캐치하셨네요! 다른 오류는 정말 사소한거였어서 찾으실 수 있어요! 힌트를 더 드리자면 메인에서 입력을 받을 때 문제가 있었어요

2021-09-28 13:58 UTC, kimyu0218 commented
1759번, 15661번, 2580번 수정했습니다!!

정말 간단한 오류였는데 못 찾고 있었네요..ㅎㅎ.. 감사합니다

2021-09-28 14:56 UTC, HyunJiLim0406 reviewed
p3
수고하셨습니다! 이제 머지하셔도 돼요~
6문제 다 푸셨으니 쿠폰도 기록할게요

2021-09-28 15:09 UTC, merged